/**
 * Trend Forecaster Service
 *
 * Mocks the Vertex AI Trend Forecaster component. In production this calls
 * a fine-tuned time-series model on Vertex AI. Here we simulate realistic
 * forecasts with domain logic and controlled randomness.
 *
 * Forecast horizon: 7 days.
 */

// Category-level seasonal multipliers for Raipur (monsoon = Jul-Sep, dry = Feb-May)
function getSeasonalMultiplier(category) {
  const month = new Date().getMonth(); // 0-indexed
  const monsoon = month >= 6 && month <= 8; // Jul–Sep
  const preMonsoon = month >= 3 && month <= 5; // Apr–Jun

  const multipliers = {
    water:          monsoon ? 1.6 : preMonsoon ? 1.3 : 0.9,
    food:           monsoon ? 1.4 : preMonsoon ? 1.1 : 1.0,
    health:         monsoon ? 1.5 : preMonsoon ? 1.2 : 0.8,
    shelter:        monsoon ? 1.7 : 1.0,
    infrastructure: monsoon ? 1.8 : preMonsoon ? 1.1 : 0.7,
    air:            monsoon ? 0.8 : preMonsoon ? 1.3 : 1.4,
    // New civic categories
    electricity:    monsoon ? 1.4 : preMonsoon ? 1.0 : 0.9,
    roads:          monsoon ? 1.6 : preMonsoon ? 1.1 : 0.8,
    sanitation:     monsoon ? 1.7 : preMonsoon ? 1.2 : 0.9,
  };

  return multipliers[category] ?? 1.0;
}

/**
 * Generate a 7-day report count forecast for a given category.
 * Uses simple exponential smoothing + seasonal adjustment + noise.
 *
 * @param {object[]} historicalReports  - all reports in the store
 * @param {string} category
 * @returns {{ days: object[], summary: string, peakDay: number, confidence: number }}
 */
function forecastCategory(historicalReports, category) {
  const catReports = historicalReports.filter((r) => r.category === category);
  const baseline = catReports.length > 0 ? catReports.length / 7 : 1; // avg reports/day over week
  const seasonal = getSeasonalMultiplier(category);
  const confidence = Math.round(62 + Math.random() * 28); // 62–90%

  const days = Array.from({ length: 7 }, (_, i) => {
    const dayLabel = new Date(Date.now() + i * 86_400_000).toLocaleDateString('en-IN', {
      weekday: 'short',
      month: 'short',
      day: 'numeric',
    });

    // Slight upward trend mid-week, noise
    const weekdayFactor = [1.0, 1.1, 1.15, 1.1, 1.05, 0.9, 0.85][i];
    const noise = 1 + (Math.random() - 0.5) * 0.3;
    const predicted = Math.round(baseline * seasonal * weekdayFactor * noise * 10) / 10;

    return { day: dayLabel, dayIndex: i, predicted: Math.max(0.1, predicted) };
  });

  const peakDay = days.reduce((max, d) => (d.predicted > max.predicted ? d : max), days[0]);

  const trendDirection = days[6].predicted > days[0].predicted ? 'rising' : 'falling';
  const summary = `${category} need is ${trendDirection} this week. Peak expected on ${peakDay.day}. Seasonal multiplier: ${seasonal.toFixed(1)}x.`;

  return { days, summary, peakDay: peakDay.dayIndex, confidence };
}

/**
 * Full forecast across all categories.
 *
 * @param {object[]} reports
 * @returns {object}
 */
function generateForecast(reports) {
  const categories = ['food', 'water', 'health', 'shelter', 'infrastructure', 'air', 'electricity', 'roads', 'sanitation'];

  const forecasts = {};
  for (const cat of categories) {
    forecasts[cat] = forecastCategory(reports, cat);
  }

  // Overall system risk level
  const avgConfidence = Math.round(
    categories.reduce((sum, c) => sum + forecasts[c].confidence, 0) / categories.length,
  );

  const highRiskCategories = categories.filter((c) => getSeasonalMultiplier(c) > 1.3);

  return {
    generatedAt: new Date().toISOString(),
    horizonDays: 7,
    forecasts,
    systemRisk: highRiskCategories.length >= 3 ? 'high' : highRiskCategories.length >= 1 ? 'medium' : 'low',
    highRiskCategories,
    avgConfidence,
    note: 'Forecast is generated by a trend model using seasonal patterns for Raipur, CG. Actual deployment uses Vertex AI fine-tuned models.',
  };
}

module.exports = { generateForecast };
