/**
 * In-memory data store with realistic seed data for Raipur, Chhattisgarh.
 * In production this would be replaced by Firebase Realtime DB / Firestore.
 *
 * Geographic context: Raipur, CG — approx. lat 21.25, lng 81.63
 */

const { v4: uuidv4 } = require('uuid');

// ─── helpers ──────────────────────────────────────────────────────────────────
const hoursAgo = (h) => new Date(Date.now() - h * 3_600_000).toISOString();
const daysAgo  = (d) => hoursAgo(d * 24);

// ─── Reports (raw community signals) ─────────────────────────────────────────
const reports = [
  {
    id: 'rpt-001',
    source: 'ngo_upload',
    category: 'food',
    title: 'Food scarcity in Tatiband flood camp',
    description:
      'Post-monsoon displacement has left ~350 people without ration access. Local shops are depleted. Families with infants are at highest risk. NGO warehouse has 70 kits available but no distribution vehicle.',
    location: { lat: 21.2389, lng: 81.6500, ward: 'Ward 12', area: 'Tatiband' },
    reportedBy: 'Sahayata Trust (NGO)',
    urgencyScore: 94,
    status: 'assigned',
    tags: ['food-insecurity', 'flood-relief', 'infants', 'displacement'],
    affectedCount: 350,
    createdAt: hoursAgo(12),
    updatedAt: hoursAgo(2),
  },
  {
    id: 'rpt-002',
    source: 'whatsapp',
    category: 'water',
    title: 'Contaminated tap water — Shankar Nagar Block B',
    description:
      'Residents report brownish, foul-smelling water from taps for 3 consecutive days. At least 40 households (~200 people) affected. Children in the area are showing signs of stomach illness. Local health worker confirmed.',
    location: { lat: 21.2514, lng: 81.6296, ward: 'Ward 7', area: 'Shankar Nagar' },
    reportedBy: '+91-9876543210',
    urgencyScore: 87,
    status: 'open',
    tags: ['contamination', 'health-risk', 'children', 'tap-water'],
    affectedCount: 200,
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(6),
  },
  {
    id: 'rpt-003',
    source: 'paper_survey',
    category: 'health',
    title: 'Dengue fever cluster — Raipur Colony',
    description:
      'Field worker survey confirms 18 dengue cases in a 2-block radius over 10 days. Stagnant water breeding sites identified at 6 locations. Vector control team has not visited. School is adjacent.',
    location: { lat: 21.2450, lng: 81.6400, ward: 'Ward 15', area: 'Raipur Colony' },
    reportedBy: 'Field Worker: Meena Sharma',
    urgencyScore: 91,
    status: 'open',
    tags: ['dengue', 'vector-control', 'stagnant-water', 'school-adjacent'],
    affectedCount: 80,
    createdAt: hoursAgo(18),
    updatedAt: hoursAgo(18),
  },
  {
    id: 'rpt-004',
    source: 'iot',
    category: 'air',
    title: 'Hazardous AQI — Urla Industrial Corridor',
    description:
      'IoT air quality sensor AQI-003 logged PM2.5 at 287 µg/m³ sustained for 4+ hours. Safe limit is 25 µg/m³ (WHO). A school with 600 students and 3 residential blocks are within 500m of the source.',
    location: { lat: 21.2600, lng: 81.6150, ward: 'Ward 3', area: 'Urla Industrial Area' },
    reportedBy: 'IoT-Sensor-AQI-003',
    urgencyScore: 79,
    status: 'open',
    tags: ['air-quality', 'industrial', 'school-nearby', 'PM2.5'],
    affectedCount: 1200,
    createdAt: hoursAgo(1),
    updatedAt: hoursAgo(1),
  },
  {
    id: 'rpt-005',
    source: 'whatsapp',
    category: 'infrastructure',
    title: 'Flooded road cuts off hospital route — Kota',
    description:
      'Main road to District Hospital flooded 1.2m deep. Ambulances unable to pass. Three villages completely cut off. Alternate route adds 45 min of travel. One patient reportedly missed dialysis.',
    location: { lat: 21.2300, lng: 81.6700, ward: 'Ward 22', area: 'Kota' },
    reportedBy: '+91-9812345678',
    urgencyScore: 96,
    status: 'completed',
    tags: ['flood', 'road-block', 'hospital-access', 'emergency'],
    affectedCount: 3000,
    createdAt: daysAgo(2),
    updatedAt: hoursAgo(4),
  },
  {
    id: 'rpt-006',
    source: 'ngo_upload',
    category: 'shelter',
    title: 'Families displaced — Kurud Road demolition',
    description:
      'Municipal demolition displaced 60 families (approx 250 people). Currently sheltering under a school shed. No sanitation facilities. Children are missing school. Rainy season forecast increases urgency.',
    location: { lat: 21.2550, lng: 81.6350, ward: 'Ward 9', area: 'Kurud Road' },
    reportedBy: 'Asha Foundation (NGO)',
    urgencyScore: 72,
    status: 'open',
    tags: ['displacement', 'shelter', 'sanitation', 'children', 'demolition'],
    affectedCount: 250,
    createdAt: hoursAgo(8),
    updatedAt: hoursAgo(8),
  },
  {
    id: 'rpt-007',
    source: 'whatsapp',
    category: 'health',
    title: 'Elderly isolation in Pandri — no medicine access',
    description:
      'Caretaker reports 12 elderly residents in Pandri who have not received monthly medicine supplies for 6 weeks. Diabetes and hypertension patients at risk. Mobile clinic not operational.',
    location: { lat: 21.2460, lng: 81.6500, ward: 'Ward 18', area: 'Pandri' },
    reportedBy: '+91-9922334455',
    urgencyScore: 68,
    status: 'open',
    tags: ['elderly', 'medicine', 'chronic-illness', 'isolation'],
    affectedCount: 12,
    createdAt: hoursAgo(30),
    updatedAt: hoursAgo(30),
  },
  {
    id: 'rpt-008',
    source: 'iot',
    category: 'water',
    title: 'Low reservoir level — Telibandha Zone',
    description:
      'IoT sensor FLOW-012 reports Telibandha supply reservoir at 18% capacity. Current consumption rate gives 4 days supply remaining. Pre-monsoon gap. 8,000 households at risk.',
    location: { lat: 21.2520, lng: 81.6580, ward: 'Ward 19', area: 'Telibandha' },
    reportedBy: 'IoT-Sensor-FLOW-012',
    urgencyScore: 83,
    status: 'open',
    tags: ['water-supply', 'reservoir', 'shortage', 'critical'],
    affectedCount: 8000,
    createdAt: hoursAgo(3),
    updatedAt: hoursAgo(3),
  },
];

// ─── Volunteers ───────────────────────────────────────────────────────────────
const volunteers = [
  {
    id: 'vol-001',
    name: 'Arjun Mehta',
    phone: '+91-9801234567',
    email: 'arjun.mehta@example.com',
    skills: ['medical', 'first-aid', 'translation-hindi', 'counseling'],
    availability: 'weekends',
    location: { lat: 21.2500, lng: 81.6300, ward: 'Ward 7', area: 'Shankar Nagar' },
    rating: 4.8,
    tasksCompleted: 23,
    status: 'available',
    joinedAt: daysAgo(90),
  },
  {
    id: 'vol-002',
    name: 'Priya Nair',
    phone: '+91-9812345000',
    email: 'priya.nair@example.com',
    skills: ['logistics', 'food-distribution', 'coordination', 'driving'],
    availability: 'daily',
    location: { lat: 21.2400, lng: 81.6480, ward: 'Ward 12', area: 'Tatiband' },
    rating: 4.9,
    tasksCompleted: 41,
    status: 'on-task',
    joinedAt: daysAgo(180),
  },
  {
    id: 'vol-003',
    name: 'Ravi Kumar',
    phone: '+91-9898765432',
    email: 'ravi.kumar@example.com',
    skills: ['plumbing', 'water-sanitation', 'construction', 'heavy-lifting'],
    availability: 'weekdays',
    location: { lat: 21.2520, lng: 81.6290, ward: 'Ward 7', area: 'Shankar Nagar' },
    rating: 4.6,
    tasksCompleted: 15,
    status: 'available',
    joinedAt: daysAgo(45),
  },
  {
    id: 'vol-004',
    name: 'Sunita Devi',
    phone: '+91-9870012345',
    email: 'sunita.devi@example.com',
    skills: ['medical', 'counseling', 'woman-child-welfare', 'field-survey'],
    availability: 'daily',
    location: { lat: 21.2455, lng: 81.6395, ward: 'Ward 15', area: 'Raipur Colony' },
    rating: 5.0,
    tasksCompleted: 67,
    status: 'available',
    joinedAt: daysAgo(365),
  },
  {
    id: 'vol-005',
    name: 'Deepak Sahu',
    phone: '+91-9900011122',
    email: 'deepak.sahu@example.com',
    skills: ['driving', 'logistics', 'heavy-lifting', 'shelter-setup'],
    availability: 'weekends',
    location: { lat: 21.2310, lng: 81.6690, ward: 'Ward 22', area: 'Kota' },
    rating: 4.3,
    tasksCompleted: 9,
    status: 'available',
    joinedAt: daysAgo(20),
  },
  {
    id: 'vol-006',
    name: 'Kavita Bose',
    phone: '+91-9711223344',
    email: 'kavita.bose@example.com',
    skills: ['education', 'child-welfare', 'documentation', 'translation-bengali'],
    availability: 'daily',
    location: { lat: 21.2550, lng: 81.6360, ward: 'Ward 9', area: 'Kurud Road' },
    rating: 4.7,
    tasksCompleted: 32,
    status: 'available',
    joinedAt: daysAgo(120),
  },
  {
    id: 'vol-007',
    name: 'Suresh Patel',
    phone: '+91-9833445566',
    email: 'suresh.patel@example.com',
    skills: ['medical', 'elderly-care', 'medicine-distribution', 'first-aid'],
    availability: 'weekdays',
    location: { lat: 21.2465, lng: 81.6510, ward: 'Ward 18', area: 'Pandri' },
    rating: 4.5,
    tasksCompleted: 19,
    status: 'available',
    joinedAt: daysAgo(60),
  },
];

// ─── Tasks (generated by AI engine from reports) ──────────────────────────────
const tasks = [
  {
    id: 'tsk-001',
    reportId: 'rpt-001',
    title: 'Emergency food kit distribution — Tatiband Flood Camp',
    description:
      'Distribute 70 ration kits stored at District Warehouse Block-C to flood victims at Tatiband camp. Prioritise infants and pregnant women. Collect acknowledgement signatures for NGO records.',
    category: 'food',
    urgencyScore: 94,
    status: 'in-progress',
    assignedVolunteerId: 'vol-002',
    estimatedHours: 6,
    location: { lat: 21.2389, lng: 81.6500, area: 'Tatiband' },
    sdgGoals: [1, 2, 3],
    createdAt: hoursAgo(10),
    updatedAt: hoursAgo(2),
    completedAt: null,
  },
  {
    id: 'tsk-002',
    reportId: 'rpt-002',
    title: 'Water sample collection — Shankar Nagar Block B',
    description:
      'Collect samples from 5 marked tap points using provided sterile kits (available at Ward 7 PHC). Label with GPS coordinates and submit to District Health Lab by 5pm. Document household health symptoms.',
    category: 'water',
    urgencyScore: 87,
    status: 'open',
    assignedVolunteerId: null,
    estimatedHours: 3,
    location: { lat: 21.2514, lng: 81.6296, area: 'Shankar Nagar' },
    sdgGoals: [3, 6, 11],
    createdAt: hoursAgo(5),
    updatedAt: hoursAgo(5),
    completedAt: null,
  },
  {
    id: 'tsk-003',
    reportId: 'rpt-003',
    title: 'Dengue awareness + breeding site mapping — Raipur Colony',
    description:
      'Door-to-door awareness in Blocks 14-A and 14-B. Distribute dengue prevention pamphlets (Ward 15 office). GPS-tag all stagnant water sources found. Submit report to vector control team.',
    category: 'health',
    urgencyScore: 91,
    status: 'open',
    assignedVolunteerId: null,
    estimatedHours: 4,
    location: { lat: 21.2450, lng: 81.6400, area: 'Raipur Colony' },
    sdgGoals: [3, 11],
    createdAt: hoursAgo(15),
    updatedAt: hoursAgo(15),
    completedAt: null,
  },
  {
    id: 'tsk-004',
    reportId: 'rpt-006',
    title: 'Temporary shelter assistance — Kurud Road families',
    description:
      'Assist 60 displaced families with tarp and bamboo shelter setup. Materials are at Ward 9 community centre. Contact NGO coordinator (Kavita: 9711223344) before arriving. Document family count.',
    category: 'shelter',
    urgencyScore: 72,
    status: 'open',
    assignedVolunteerId: null,
    estimatedHours: 8,
    location: { lat: 21.2550, lng: 81.6350, area: 'Kurud Road' },
    sdgGoals: [1, 10, 11],
    createdAt: hoursAgo(7),
    updatedAt: hoursAgo(7),
    completedAt: null,
  },
  {
    id: 'tsk-005',
    reportId: 'rpt-007',
    title: 'Medicine delivery — elderly residents in Pandri',
    description:
      'Collect prescribed medicines from CHC Pandri store (list provided). Home-deliver to 12 registered elderly residents. Verify with ASHA worker at each stop. Record BP/glucose readings if kit available.',
    category: 'health',
    urgencyScore: 68,
    status: 'open',
    assignedVolunteerId: null,
    estimatedHours: 3,
    location: { lat: 21.2460, lng: 81.6500, area: 'Pandri' },
    sdgGoals: [3, 10],
    createdAt: hoursAgo(28),
    updatedAt: hoursAgo(28),
    completedAt: null,
  },
  {
    id: 'tsk-006',
    reportId: 'rpt-005',
    title: 'Road clearance coordination — Kota-Hospital route',
    description:
      'Task completed. Municipal pump unit deployed. Road passable as of 16:30 hrs. Photographic evidence submitted. SDG impact logged.',
    category: 'infrastructure',
    urgencyScore: 96,
    status: 'completed',
    assignedVolunteerId: 'vol-005',
    estimatedHours: 4,
    location: { lat: 21.2300, lng: 81.6700, area: 'Kota' },
    sdgGoals: [3, 11, 17],
    createdAt: daysAgo(2),
    updatedAt: hoursAgo(4),
    completedAt: hoursAgo(4),
  },
];

// ─── SDG Impact Records ────────────────────────────────────────────────────────
const sdgImpact = {
  'sdg-1': { goal: 1, label: 'No Poverty', score: 61, trend: +4, tasksLinked: 3, peopleReached: 610 },
  'sdg-2': { goal: 2, label: 'Zero Hunger', score: 72, trend: +11, tasksLinked: 2, peopleReached: 350 },
  'sdg-3': { goal: 3, label: 'Good Health & Well-being', score: 68, trend: +7, tasksLinked: 5, peopleReached: 292 },
  'sdg-6': { goal: 6, label: 'Clean Water & Sanitation', score: 55, trend: +3, tasksLinked: 2, peopleReached: 200 },
  'sdg-10': { goal: 10, label: 'Reduced Inequalities', score: 48, trend: +2, tasksLinked: 2, peopleReached: 262 },
  'sdg-11': { goal: 11, label: 'Sustainable Cities & Communities', score: 74, trend: +9, tasksLinked: 6, peopleReached: 3512 },
  'sdg-17': { goal: 17, label: 'Partnerships for the Goals', score: 81, trend: +5, tasksLinked: 4, peopleReached: 0 },
};

module.exports = { reports, volunteers, tasks, sdgImpact };
